version: '3'
services:
    app:
        image: kaangiray26/endless:1.0
        restart: on-failure
        ports:
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            port: 3000                 # Set Port
            version: "1.0"             # Set Version
            verbose: false             # Verbose Logging
            NODE_ENV: production       # Set Node Environment
            POSTGRES_HOST: postgres    # Postgres Host/IP
            POSTGRES_USER: endless     # Set Postgres Username
            POSTGRES_PASSWORD: endless # Set Postgres Password
            POSTGRES_PORT: 5432        # Postgres Database Port
            POSTGRES_DB: endless       # Set Postgres Database Name
    postgres:
        image: kaangiray26/postgres:2.0
        restart: on-failure
        environment:
            POSTGRES_USER: endless     # Set Postgres Username
            POSTGRES_PASSWORD: endless # Set Postgres Password
            POSTGRES_DB: endless       # Set Postgres Database Name
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U endless" ]
            interval: 1s
            timeout: 5s
            retries: 5
volumes:
    db-data: